language: java
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      services:
        - docker
      before_install:
        - docker pull ibmcom/ibmjava:8-sdk
      script:
        - docker run -v `pwd`:/work ibmcom/ibmjava:8-sdk /bin/sh -c "cd work; java -version; ./mvnw clean test"

